### List API audit log entries
GET {{baseUrl}}/api/v1/audit/api?page=0&size=50
Authorization: Bearer {{accessToken}}

### List API audit log entries with query filter
GET {{baseUrl}}/api/v1/audit/api?page=0&size=50&query=GROUP_UPDATED
Authorization: Bearer {{accessToken}}

### List scaling log entries
GET {{baseUrl}}/api/v1/audit/scaling?page=0&size=50
Authorization: Bearer {{accessToken}}

### List scaling log entries with query filter
GET {{baseUrl}}/api/v1/audit/scaling?page=0&size=50&query=autoscaler
Authorization: Bearer {{accessToken}}
