@existingPermissionGroup = admin
@managedPermissionGroup = example-moderator
@managedPermission = ogcloud.command.execute
@additionalPermission = ogcloud.server.view

### List permission groups
GET {{baseUrl}}/api/v1/permissions/groups?page=0&size=50&query=admin
Authorization: Bearer {{accessToken}}

### Get a permission group by name
GET {{baseUrl}}/api/v1/permissions/groups/{{existingPermissionGroup}}
Authorization: Bearer {{accessToken}}

### Create a permission group
POST {{baseUrl}}/api/v1/permissions/groups
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "{{managedPermissionGroup}}",
  "name": "Example Moderator",
  "display": {
    "chatPrefix": "&8[&3Mod&8] ",
    "chatSuffix": "&7: &f",
    "nameColor": "&3",
    "tabPrefix": "&3Mod &8> "
  },
  "weight": 20,
  "default": false,
  "permissions": [
    {
      "perm": "{{managedPermission}}",
      "description": "Allows executing remote commands."
    }
  ]
}

### Update a permission group
PUT {{baseUrl}}/api/v1/permissions/groups/{{managedPermissionGroup}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Example Senior Moderator",
  "display": {
    "chatPrefix": "&8[&bSrMod&8] ",
    "chatSuffix": "&7: &f",
    "nameColor": "&b",
    "tabPrefix": "&bSrMod &8> "
  },
  "weight": 15,
  "default": false,
  "permissions": [
    {
      "perm": "{{managedPermission}}",
      "description": "Allows executing remote commands."
    },
    {
      "perm": "{{additionalPermission}}",
      "description": "Allows viewing server state."
    }
  ]
}

### Add a permission to a group
POST {{baseUrl}}/api/v1/permissions/groups/{{managedPermissionGroup}}/permissions
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "perm": "{{additionalPermission}}",
  "description": "Allows viewing server state."
}

### Remove a permission from a group
DELETE {{baseUrl}}/api/v1/permissions/groups/{{managedPermissionGroup}}/permissions/{{additionalPermission}}
Authorization: Bearer {{accessToken}}

### Delete a permission group
DELETE {{baseUrl}}/api/v1/permissions/groups/{{managedPermissionGroup}}
Authorization: Bearer {{accessToken}}
