@playerUuid = b903c5a8-7627-4f10-bf59-37a4f1170d9a

### List online players
GET {{baseUrl}}/api/v1/players?page=0&size=50&query=jevzo
Authorization: Bearer {{accessToken}}

### List persisted players
GET {{baseUrl}}/api/v1/players/all?page=0&size=50&query=jevzo
Authorization: Bearer {{accessToken}}

### Get a player by UUID
GET {{baseUrl}}/api/v1/players/{{playerUuid}}
Authorization: Bearer {{accessToken}}

### Set a player's permission group
PUT {{baseUrl}}/api/v1/players/{{playerUuid}}/group
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "group": "admin",
  "duration": "30d"
}

### Transfer a player
POST {{baseUrl}}/api/v1/players/{{playerUuid}}/transfer
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "target": "lobby"
}
