@serverId = e6892b8e7c4d42d2acefca7567b3826f
@serverGroup = lobby

### List servers
GET {{baseUrl}}/api/v1/servers?page=0&size=50&group={{serverGroup}}&query=lobby
Authorization: Bearer {{accessToken}}

### Get a server by ID
GET {{baseUrl}}/api/v1/servers/{{serverId}}
Authorization: Bearer {{accessToken}}

### Request a server
POST {{baseUrl}}/api/v1/servers/request
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "group": "{{serverGroup}}"
}

### Stop a server
POST {{baseUrl}}/api/v1/servers/{{serverId}}/stop
Authorization: Bearer {{accessToken}}

### Kill a server
POST {{baseUrl}}/api/v1/servers/{{serverId}}/kill
Authorization: Bearer {{accessToken}}

### Force a template push for a server
POST {{baseUrl}}/api/v1/servers/{{serverId}}/template/push
Authorization: Bearer {{accessToken}}
