### List all templates
GET {{baseUrl}}/api/v1/templates
Authorization: Bearer {{accessToken}}

### List templates with pagination and filtering
GET {{baseUrl}}/api/v1/templates?page=0&size=50&group=lobby&query=1.0
Authorization: Bearer {{accessToken}}

### Upload a template for a group
POST {{baseUrl}}/api/v1/templates/lobby/upload?version=1.0.1
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="template.tar.gz"
Content-Type: application/gzip

< ./template.tar.gz
--boundary--

### Download a template archive
GET {{baseUrl}}/api/v1/templates/lobby/1.0.1/download
Authorization: Bearer {{accessToken}}

### Delete a template archive
DELETE {{baseUrl}}/api/v1/templates/lobby/1.0.1
Authorization: Bearer {{accessToken}}
