@templateGroup = lobby
@templateVersion = 1.0.1

### List templates
GET {{baseUrl}}/api/v1/templates?page=0&size=50&group={{templateGroup}}&query=1.0
Authorization: Bearer {{accessToken}}

### Upload a template
POST {{baseUrl}}/api/v1/templates/{{templateGroup}}/upload?version={{templateVersion}}
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="template.tar.gz"
Content-Type: application/gzip

< ./template.tar.gz
--boundary--

### Download a template
GET {{baseUrl}}/api/v1/templates/{{templateGroup}}/{{templateVersion}}/download
Authorization: Bearer {{accessToken}}

### Delete a template
DELETE {{baseUrl}}/api/v1/templates/{{templateGroup}}/{{templateVersion}}
Authorization: Bearer {{accessToken}}
