{{- if .Values.api.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: {{ include "ogcloud-platform.namespace" . }}
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: ogcloud
type: Opaque
stringData:
  MINIO_ACCESS_KEY: {{ .Values.api.env.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.api.env.minioSecretKey | quote }}
  OGCLOUD_AUTH_JWT_SECRET: {{ .Values.api.env.jwtSecret | quote }}
{{- end }}
