{{- if .Values.controller.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: controller-secret
  namespace: {{ include "ogcloud-platform.namespace" . }}
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: ogcloud
type: Opaque
stringData:
  OGCLOUD_API_PASSWORD: {{ .Values.controller.env.apiPassword | quote }}
  MINIO_ACCESS_KEY: {{ .Values.controller.env.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.controller.env.minioSecretKey | quote }}
  POD_MINIO_ACCESS_KEY: {{ .Values.controller.env.podMinioAccessKey | quote }}
  POD_MINIO_SECRET_KEY: {{ .Values.controller.env.podMinioSecretKey | quote }}
  POD_OGCLOUD_API_PASSWORD: {{ default .Values.controller.env.apiPassword .Values.controller.env.podApiPassword | quote }}
{{- end }}
