{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  namespace: {{ include "ogcloud-platform.namespace" . }}
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: ogcloud
data:
  MONGODB_URI: {{ .Values.connections.mongodbUri | quote }}
  REDIS_HOST: {{ .Values.connections.redisHost | quote }}
  REDIS_PORT: {{ .Values.connections.redisPort | quote }}
  KAFKA_BROKERS: {{ .Values.connections.kafkaBrokers | quote }}
  MINIO_ENDPOINT: {{ .Values.connections.minioEndpoint | quote }}
  OGCLOUD_API_EMAIL: {{ .Values.controller.env.apiEmail | quote }}
  OGCLOUD_NAMESPACE: {{ include "ogcloud-platform.namespace" . | quote }}
  POD_MINIO_ENDPOINT: {{ .Values.controller.env.podMinioEndpoint | quote }}
  POD_KAFKA_BROKERS: {{ .Values.controller.env.podKafkaBrokers | quote }}
  POD_OGCLOUD_KAFKA_CONSUMER_RESTART_INITIAL_BACKOFF_MS: {{ .Values.controller.env.podKafkaConsumerRestartInitialBackoffMs | quote }}
  POD_OGCLOUD_KAFKA_CONSUMER_RESTART_MAX_BACKOFF_MS: {{ .Values.controller.env.podKafkaConsumerRestartMaxBackoffMs | quote }}
  POD_OGCLOUD_KAFKA_CONSUMER_RESTART_JITTER_MS: {{ .Values.controller.env.podKafkaConsumerRestartJitterMs | quote }}
  POD_REDIS_HOST: {{ .Values.controller.env.podRedisHost | quote }}
  POD_REDIS_PORT: {{ .Values.controller.env.podRedisPort | quote }}
  POD_MONGODB_URI: {{ .Values.controller.env.podMongodbUri | quote }}
  POD_API_URL: {{ .Values.controller.env.podApiUrl | quote }}
  POD_OGCLOUD_API_EMAIL: {{ default .Values.controller.env.apiEmail .Values.controller.env.podApiEmail | quote }}
  OGCLOUD_KAFKA_BUSY_CONCURRENCY: {{ .Values.controller.env.kafkaBusyConcurrency | quote }}
  OGCLOUD_KAFKA_BUSY_MAX_POLL_RECORDS: {{ .Values.controller.env.kafkaBusyMaxPollRecords | quote }}
  OGCLOUD_KAFKA_LIGHT_CONCURRENCY: {{ .Values.controller.env.kafkaLightConcurrency | quote }}
  OGCLOUD_KAFKA_LIGHT_MAX_POLL_RECORDS: {{ .Values.controller.env.kafkaLightMaxPollRecords | quote }}
  OGCLOUD_KAFKA_SINGLE_CONCURRENCY: {{ .Values.controller.env.kafkaSingleConcurrency | quote }}
  OGCLOUD_KAFKA_SINGLE_MAX_POLL_RECORDS: {{ .Values.controller.env.kafkaSingleMaxPollRecords | quote }}
  OGCLOUD_KAFKA_MAX_POLL_INTERVAL_MS: {{ .Values.controller.env.kafkaMaxPollIntervalMs | quote }}
  OGCLOUD_KAFKA_SESSION_TIMEOUT_MS: {{ .Values.controller.env.kafkaSessionTimeoutMs | quote }}
  OGCLOUD_KAFKA_HEARTBEAT_INTERVAL_MS: {{ .Values.controller.env.kafkaHeartbeatIntervalMs | quote }}
  OGCLOUD_KAFKA_LISTENER_POLL_TIMEOUT_MS: {{ .Values.controller.env.kafkaListenerPollTimeoutMs | quote }}
  OGCLOUD_KAFKA_RETRY_MAX_RETRIES: {{ .Values.controller.env.kafkaRetryMaxRetries | quote }}
  OGCLOUD_KAFKA_RETRY_BACKOFF_MS: {{ .Values.controller.env.kafkaRetryBackoffMs | quote }}
{{- end }}
