{{- if .Values.loadbalancer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: loadbalancer-secret
  namespace: {{ include "ogcloud-platform.namespace" . }}
  labels:
    app.kubernetes.io/name: loadbalancer
    app.kubernetes.io/part-of: ogcloud
type: Opaque
stringData:
  OGCLOUD_API_PASSWORD: {{ .Values.loadbalancer.env.apiPassword | quote }}
{{- end }}
