{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-auth
  namespace: {{ include "ogcloud-infra.namespace" . }}
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: ogcloud
type: Opaque
data:
  access-key: {{ .Values.minio.rootCredentials.accessKey | b64enc | quote }}
  secret-key: {{ .Values.minio.rootCredentials.secretKey | b64enc | quote }}
{{- end }}
